<footer id='page-footer-placeholder'>
</footer>
<footer id='page-footer'>
  <div>
  <a href="http://theinitium.com/">Initium Media</a> 
	&nbsp; &nbsp; | &nbsp; &nbsp;
  <a href="/blog/feed.xml">RSS</a>
	&nbsp; &nbsp; | &nbsp; &nbsp;
  <a href="/about/">Newsletter</a> 
	&nbsp; &nbsp; | &nbsp; &nbsp;
  <a href="/career/">Career</a> 
  </div>
  <div>© Initium Lab. All rights reserved 2016.</div>
</footer>

{% include '../_scripts/email_setting.swig' %}
